WITH EMP_DAILY_TIMES AS 
(
    SELECT E.EVENT_DAY AS DAY, E.EMP_ID, (E.OUT_TIME-E.IN_TIME) AS DAILY_TIME
    FROM EMPLOYEES E
)
SELECT E.DAY, E.EMP_ID, SUM(DAILY_TIME) TOTAL_TIME
FROM EMP_DAILY_TIMES E
GROUP BY E.DAY, E.EMP_ID;