SELECT S.NAME
FROM SALESPERSON S
WHERE S.SALES_ID NOT IN (
    SELECT O.SALES_ID
    FROM ORDERS O
    WHERE O.COM_ID = (
        SELECT C.COM_ID
        FROM COMPANY C
        WHERE C.NAME = 'RED'
    )
);