# find department-wise, highest 3 distinct salaries
WITH EMP_DEPT AS (
    SELECT 
        E.NAME EMPLOYEE, E.SALARY, 
        E.DEPARTMENTID, D.NAME DEPARTMENT,
        DENSE_RANK() OVER(PARTITION BY E.DEPARTMENTID ORDER BY E.SALARY DESC) RNK
    FROM EMPLOYEE E, DEPARTMENT D
    WHERE E.DEPARTMENTID = D.ID
)
SELECT DEPARTMENT, EMPLOYEE, SALARY
FROM EMP_DEPT
WHERE RNK <= 3;