WITH AGG AS(
    SELECT O.CUSTOMER_NUMBER, COUNT(O.ORDER_NUMBER) CNT
    FROM ORDERS O
    GROUP BY O.CUSTOMER_NUMBER
)
SELECT A.CUSTOMER_NUMBER
FROM AGG A
WHERE A.CNT = (SELECT MAX(A2.CNT) FROM AGG A2);