SELECT U.USER_ID BUYER_ID, U.JOIN_DATE, COALESCE(COUNT(O.ORDER_ID),0) ORDERS_IN_2019
FROM USERS U
LEFT JOIN ORDERS O
ON U.USER_ID = O.BUYER_ID
AND O.ORDER_DATE LIKE '%2019%'
GROUP BY U.USER_ID, U.JOIN_DATE;