WITH USER_TRANS AS (
    SELECT U.NAME, SUM(T.AMOUNT) BALANCE
    FROM USERS U, TRANSACTIONS T
    WHERE U.ACCOUNT = T.ACCOUNT
    GROUP BY U.NAME
)
SELECT UT.NAME, UT.BALANCE
FROM USER_TRANS UT
WHERE UT.BALANCE > 10000;