# WHERE T.ID NOT IN (SELECT ID FROM ROOT UNION SELECT ID FROM LEAVES)
SELECT DISTINCT 
    T.ID,
    CASE 
        WHEN T.P_ID IS NULL THEN 'Root'
        WHEN T.ID IN ( SELECT T2.P_ID FROM TREE T2 ) THEN 'Inner'
        ELSE 'Leaf'
    END TYPE
FROM TREE T;