SELECT P.PRODUCT_ID, 'store1' STORE, P.STORE1 PRICE
FROM PRODUCTS P
WHERE P.STORE1 IS NOT NULL
UNION ALL
SELECT P.PRODUCT_ID, 'store2' STORE, P.STORE2 PRICE
FROM PRODUCTS P
WHERE P.STORE2 IS NOT NULL
UNION ALL
SELECT P.PRODUCT_ID, 'store3' STORE, P.STORE3 PRICE
FROM PRODUCTS P
WHERE P.STORE3 IS NOT NULL;