# Create 2 new columns for lagged values
WITH CTE AS (
    SELECT L.ID, L.NUM FIRST_NUM, LAG(NUM, 1) OVER(ORDER BY ID) SECOND_NUM, LAG(NUM, 2) OVER(ORDER BY ID) THIRD_NUM
    FROM LOGS L
)
SELECT DISTINCT CTE.FIRST_NUM CONSECUTIVENUMS
FROM CTE
WHERE CTE.FIRST_NUM = CTE.SECOND_NUM 
AND CTE.FIRST_NUM = CTE.THIRD_NUM;